# Generated by Django 3.0.5 on 2021-06-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=50, verbose_name='State Name')),
                ('stateAbbreviation', models.CharField(max_length=3, verbose_name='State Abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractionName', models.CharField(max_length=200, verbose_name='Attraction Name')),
                ('homeState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristAttractions.State', verbose_name='Home State')),
            ],
        ),
    ]
