# Generated by Django 3.0.5 on 2021-06-24 03:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djitney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='last_cleaned_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 3, 5, 52, 707248, tzinfo=utc)),
        ),
    ]
