# Generated by Django 3.0.5 on 2021-07-05 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djitney', '0004_auto_20210624_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='schedule',
            field=models.TimeField(default=datetime.datetime(2021, 7, 5, 21, 41, 41, 434741, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='station',
            name='last_cleaned_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 5, 21, 41, 41, 435037, tzinfo=utc)),
        ),
    ]
