# Generated by Django 3.0.5 on 2021-07-06 03:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djitney', '0005_auto_20210705_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='schedule',
            field=models.TimeField(default=datetime.datetime(2021, 7, 6, 3, 31, 33, 543172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='station',
            name='last_cleaned_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 3, 31, 33, 543517, tzinfo=utc)),
        ),
    ]
